-- Local/dev seed. Applied by `supabase start` and `supabase db reset`.
--
-- Intentionally EMPTY: every account is born through a real flow, never seeded
-- bare. Seeding accounts with no identity (no auth.users) and no membership
-- contradicts the model and is misleading in the dashboard:
--   * customer org  → a user signs up and runs `/id/create-organization`
--                     (becomes that org's customer-admin), or is invited by email
--   * staff account → bootstrap owner (BOOTSTRAP_OWNER_EMAIL on first sign-in)
--                     or an email invitation
--
-- So to get data locally, use the apps: sign up / sign in (e.g. the bootstrap
-- owner owner@local.dev) and create orgs / invite members. Tests provision their
-- own data (e.g. the RLS specs create users via the local admin API); nothing
-- depends on seeded rows.
